services:
  spark-master:
    build:
      context: ./spark
    container_name: "spark-master"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - airflow_0fa3c0_airflow

  spark-worker-1:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - airflow_0fa3c0_airflow

  spark-worker-2:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - airflow_0fa3c0_airflow

#  minio:
#    hostname: minio
#    image: quay.io/minio/minio:RELEASE.2024-01-18T22-51-28Z
#    container_name: minio
#    ports:
#      - "9001:9001"
#      - "9000:9000"
#    command: [ "server", "/data", "--console-address", ":9001" ]
#    volumes:
#      - ./minio:/data
#    environment:
#      - MINIO_ROOT_USER=minio
#      - MINIO_ROOT_PASSWORD=minio123
#      - MINIO_ACCESS_KEY=minio
#      - MINIO_SECRET_KEY=minio123
#    networks:
#      - airflow_0fa3c0_airflow

networks:
  airflow_0fa3c0_airflow:
#    driver: bridge
#    name: airflow_0fa3c0_airflow
